export const SEARCH = "SEARCH_BY_PROVINCE";
export const SEARCH_SUCCESS = "SEARCH_BY_PROVINCE_SUCCESS";
export const SEARCH_FAILED = "SEARCH_BY_PROVINCE_FAILED";

export const RESET_DATA = "RESET_DATA_SEARCH_BY_PROVINCE";
